-- MOC Restaurant v1.1.x -> v1.2.0 upgrade
ALTER TABLE `moc_menu`
    ADD COLUMN IF NOT EXISTS `category` VARCHAR(50) NOT NULL DEFAULT 'Menu',
    ADD COLUMN IF NOT EXISTS `enabled` TINYINT(1) NOT NULL DEFAULT 1;

ALTER TABLE `moc_orders`
    ADD COLUMN IF NOT EXISTS `employee` VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS `order_type` VARCHAR(30) NOT NULL DEFAULT 'counter',
    ADD COLUMN IF NOT EXISTS `payment_type` VARCHAR(20) NULL,
    ADD COLUMN IF NOT EXISTS `subtotal` INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS `tax` INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS `total` INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS `idx_moc_orders_status` ON `moc_orders` (`status`);
